import type {Metadata} from "next";
import {Geist_Mono,Inter} from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",

})

export const metadata: Metadata = {
  title: "AiPicture",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true"
        className={`${inter.className} ${geistMono.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
